version: "3.6"

x-backend-variables: &backend-variables
  DATABASE_URL:

services:
  api-gymlabs-dev:
    container_name: api-gymlabs-dev
    image: ghcr.io/gymlabs/core.api:main
    environment: *backend-variables
    restart: always
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gymlabs-dev.rule=Host(`api.gymlabs.de`)"
      - "traefik.http.routers.api-gymlabs-dev.entrypoints=websecure"
      - "traefik.http.services.api-gymlabs-dev.loadbalancer.server.port=8000"
      - "traefik.http.routers.api-gymlabs-dev.service=api-gymlabs-dev"
      - "traefik.http.routers.api-gymlabs-dev.tls.certresolver=myresolver"

networks:
  public:
    external: true
