name: Check

on:
  push:
    branches:
      - main
      - preview
      - setup-lightsail

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          aws --version
          aws lightsail get-instances
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          tags: gymlabs/api:latest