name: Create Docker Image and Deploy to Lightsail

on:
  push:
    branches:
      - main
      - preview
      - optimize-docker-image

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          aws --version
          sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          load: true
          tags: api-gymlabs-de:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: List docker images
        run: docker images

      - name: Deploy to Lightsail
        run: |
          aws lightsail get-container-services
          aws lightsail push-container-image --region eu-central-1 --service-name api-gymlabs-de --label api-gymlabs-de-latest --image api-gymlabs-de:latest
          aws lightsail get-container-images --service-name api-gymlabs-de | jq --raw-output ".containerImages[0].image" > image.txt
          cat image.txt
          jq --arg IMAGE $(cat image.txt) --arg DATABASE_URL $(echo $DATABASE_URL) '.containers.api.image = $IMAGE | .containers.api.environment.DATABASE_URL = $DATABASE_URL' container.template.json > container.json
          cat container.json
          aws lightsail create-container-service-deployment --cli-input-json file://container.json  
          
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
