# TODO: Add DATABASE_URL from secrets to container.json
name: Create Docker Image and Deploy to Lightsail

on:
  push:
    branches:
      - main
      - preview
      - setup-lightsail

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          aws --version
          sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Build
      #   uses: docker/build-push-action@v4.0.0
      #   with:
      #     context: .
      #     push: false
      #     tags: api-gymlabs-de:latest
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build Docker Image
        run: docker build -t api-gymlabs-de:latest .

      - name: List docker images
        run: docker images

      - name: Deploy to Lightsail
        run: |
          aws lightsail get-container-services
          aws --debug lightsail push-container-image --region eu-central-1 --service-name api-gymlabs-de --label api-gymlabs-de-latest --image api-gymlabs-de:latest
          aws lightsail get-container-images --service-name api-gymlabs-de | jq --raw-output ".containerImages[0].image" > image.txt
          cat image.txt
          jq --arg IMAGE $(cat image.txt) --arg DATABASE_URL $(echo $DATABASE_URL) '.containers.api.image = $IMAGE | .containers.api.environment.DATABASE_URL = $DATABASE_URL' container.template.json > container.json
          cat container.json
          json_string="'$(jq -c . container.json | sed 's/"/\\"/g')'"
          echo "JSON_STRING=$json_string" >> $GITHUB_ENV
          aws --debug lightsail create-container-service-deployment --cli-input-json $(cat container.json)
          
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
