name: Check

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci

      # clean this up
      - name: Build & install packages
        run: |
          npm run build
          npm i

      - name: Lint & check Formatting
        run: |
          npm run lint
          npm run format:check
