name: Check

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node & npm
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: "@gymlabs"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      # clean this up
      - name: Build & install packages
        run: |
          npm run build
          npm i

      - name: Lint & check Formatting
        run: |
          npm run lint
          npm run format:check
