name: Check

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate with GitHub Package Registry
        run: echo -e "@gymlabs:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
      - name: Install dependencies
        run: npm ci

      # clean this up
      - name: Build & install packages
        run: |
          npm run build
          npm i

      - name: Lint & check Formatting
        run: |
          npm run lint
          npm run format:check
