name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - preview

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: "@gymlabs"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Build packages
        run: npm run build

      - name: Publish package
        run: lerna publish from-package --yes --no-private --conventional-commits --no-verify-access
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
